version: '3'
services:
  suaipisuai:
    image: nginx
    container_name: suaipisuai
    expose:
      - 80
    volumes:
      - ./suaipisuai:/var/www/html
      - .dockerconfig/nginx/conf.d/suaipisuai.conf:/etc/nginx/nginx.conf
    environment:
      VIRTUAL_HOST: 'suaipisuai.com'

  php:
    build: .dockerconfig/php
    volumes:
      - .dockerconfig/php/conf.d:/user/local/etc/php/conf.d
      - ./html:/var/www/html
    expose:
      - 9000

  networks:
    default:
      external:
        name: sandbox_network
