version: '2'
services:
  suaipisuai:
    image: nginx
    container_name: suaipisuai
    expose:
      - 80
    volumes:
      - ./suaipisuai:/var/www/html
      - .dockerconfig/nginx/conf.d/suaipisuai.conf:/etc/nginx/nginx.conf
    environment:
      VIRTUAL_HOST: 'suaipisuai.com'

  networks:
  default:
    external:
      name: sandbox_network

