version: '3.1'
services:
  nginx:
    image: nginx
    volumes:
      - .dockerconfig/nginx/conf.d:/etc/nginx/conf.d
      - ./suaipisuai:/var/www/html
    ports:
      - "80:80"

  php:
    build: .dockerconfig/php
    volumes:
      - .dockerconfig/php/conf.d:/user/local/etc/php/conf.d
      - ./suaipisuai:/var/www/html
    expose:
      - 9000

